<div><h5>19.10.12</h5><h1>Too fast! Too fast!</h1></div><p>remember the 'pretty little user agent'? I swear I'm not a creeper – I don't refer to all attributes like a serial killer – just the ones I keep at the bottom of a well and throw lotion down to. (HAH) murder aside, remember how we had all the fun with the different between document.ready() being fired after the javascript document was loaded? well, here's another hilarious too-quick-for-humans computer joke that busted my balls for a hair too long.</p>

<p>I like webfonts. they're pretty, and make my life as a designer-turned-programmer wondrous. the things I can make! I'm responsible with them, of course: I control font-weight for headers in firefox, I convert for all platforms with the paul irish styling theorem, I make way for plenty of painless fallbacks in older browsers without anti-aliasing, and I include it before my CSS document so everything is automatically cached. despite this however, they're still files being brought in after the fact: and this will bite you in the ass if you're not careful.</p>

<p>in making of a site that relies on Ariel Felser's jquery scrollTo plugin, I found myself interested in the positions of the divs I wanted to scroll to, so I threw the five divs through an each loop, and stored their offset().top positions in a nice little array, which I then passed to the scrollTo plugin to scroll to accordingly.</p>

<p>but, to my surprise, on attempting to move around to the desired location, I noticed that it was a little off. not a whole lot at first, but as the divs got farther down the page, the discrepancies were unbearable. I took my code apart bit by bit, and scoured variables and locations alike with the console, all to no avail. what the fuck?</p>

<p>having put the each loop in the document.ready() seemed to be the place that such a loop would optimally want to be. but it turns out that differing webfonts are applied at the very end of everything, and definitely after my each loop has ran. this hilariously results in my heights being calculated with times new roman line heights, not my web font line heights.</p>

<p>the solution? throw the each loop into a setTimeout of a half second, to wait for the style to be applied. then get your positions. just a pinch of time is enough breathing room for the browser to set your type the appropriate size, the likes of which you'll see and later (ha ha) depend on.</p>
