<h5>29.12.13</h5><h1>A letter to Daniel Sauter</h1><p>mr. daniel sauter.</p>

<p>I do hope this finds you in good health. I apologize that I have not kept in contact better than I have since our time together, but my journey has thus far kept me from such things. as I sit on a train in the middle of switzerland, next to my wife, on our way to go visit her parents for the holidays: it is my plan to rectify this.</p>

<p>indeed, as I might have mentioned in a previous email, I have returned to switzerland, and have married the lovely swiss woman who I so unceremoniously dragged to one of your lectures. we first landed in Schaffhausen with the intent of making a quick stop, but ended up staying for almost two years. you may recognize Schaffhausen as the conspicuous wart at the top of Switzerland, more in Germany than otherwise, and culturally in its own awkward grey area. finding ourselves there was primarily due to Carina finding a job in the town; our stay was further prolonged by a serendipitous turn of fate called AWE, and their need for someone to make them websites. astounded at my luck, I obliged.</p>

<p>there were very, very good people there. they (for the most part) accepted me with open arms, and I made them a lot of mostly forgettable websites, and a handful of very cool ones. we travelled to portugal together, went to concerts together, and taught each other much in the way of business, friendship, design, its absence respectively, among other things. I was equally blessed by the companionship of one Roman Wüest, a programmer of little notoriety (by his own decision) but of incredible intellect. while his aesthetic tastes are the slightest bit lacking; as with your classes, I found myself once again surrounded by gracious people from which I learned a staggering amount. it was a rather unfortunate turn of events that resulted in my path and that of the agency diverging, but it ended up being precisely the correct moment for us to part ways.</p>

<p>the ensuing chaos of transition brought me to the city of Bern, and with it a marked step of culture and population further from Schaffhausen. I'm sure you know Zürich to be the larger of Swiss cities, plentiful indeed with opportunity, but it was a small agency by the name of Nothing Interactive that eventually swayed my opinion, and led us to where we currently reside. Carina was at that time also without work, permitting the transition without a tremendous amount of drama. what was ultimately the deciding factor was the propensity to create large, beautiful and interesting things, with the help of a largely developer / programmer oriented staff. they were in need of both a designer and a front end developer, of which both positions I have since been occupying.</p>

<p>this, as you may imagine, has been quite the ordeal. due to the extremely flat structure of the agency, I find myself wearing many hats, occasionally simultaneously: I am visual designer, experience designer, front end developer, back end developer, manager, micromanager, requirement architect, data architect; and then some. this has proven to be rather stressful at times, particularly with the lead of a very eager and very dedicated boss. the agency is also undergoing the transition to a more agile form of development, in which designers and developers work hand in hand, employing as much transparency as possible. indeed, UIC's design program made a couple valiant attempts to teach us how to work collaboratively; but only with other visually creative folk, all with our own classroom-sized egos. thus, working in harmony with aesthetically-stunted programmers has been quite the shock – particularly when considering that my prior experience found me at the last step of the waterfall process – but at the very least I can say that I am learning.</p>

<p>in the meantime, having acquired the taste of part-time independent work during my final months in Schaffhausen, I once again find myself working 4 days a week for my agency, and another 2 for myself. in this time, I have created my own blog and its backend from scratch, my own digital business card from scratch, and a sizable portion of my portfolio website and its backend from scratch (the likes of which is unfortunately still not online). this is to say nothing of the portfolio website and its backend I have handcrafted for my lovely wife and her creative pursuits, and the other bits and pieces of minutiae. having been quite fascinated by the many technologies and languages that you and mr. Obelleiro strived so fearlessly to teach us disheartened souls, I find myself still experimenting heavily with all things learned during my final year at UIC. it has become the foundation of my practice, and the basis with which I attempt to continue to make the world a little more beautiful, bit by ever-loving bit.</p>

<p>such a fever pitch of creation has admittedly left me rather drained however, as I realize that I am only human, and far beyond the safe haven that academia offers. I have since found myself traveling in spain, portugal, france, greece, italy and germany to keep myself balanced, as well as the obligatory (but scant few) trips back to chicago to visit and tend to my american life; but have yet to strike a truly fruitful balance between work and play. I enjoy what I do so dearly that I find myself occupied with it on my time off: but I also find myself back at work on too many monday mornings, asked to pick up where I left off on the prior friday, at the same pace. my wife has been a tremendous resource in getting me out of the house to explore the equally-tremendous resource of nature that this country is in surplus of – but her influence dwindles as the weeks become more strenuous, and as the weekends become more oriented towards recovery. indeed, I have long since tossed around the idea of once again changing jobs, unsure if I possess the wherewithal to go through another jarring transition; perhaps this is simply the life that we are withdrawn to?</p>

<p>this is not to say that it has always been such a panic. for starters, I have found quite a bit of joy in learning swiss german. I do miss being able to approach a native on the street and speak to him in my mother tongue; but being able to speak to him in his mother tongue is exhilarating. I'm sure you can relate to this experience. and, as previously mentioned, the plethora of wonderful people that I have had the pleasure to meet and continue to meet have been the most wonderful, accepting folk that I have come across yet. the time I've spent with all of them are the stuff of legends, otherwise unbelievable had it not actually happened to me. the depth of their resource knows no bounds, and I am perpetually at a loss of words to describe the community among which I find myself.</p>

<p>in short, the last two-years-and-some-change have been a study in aesthetic enlightenment, panicked fervor, undying passion and the magnitude to which mania can affect all of the above.</p>

<p>I do hope that the years have been good to you, good sir. the debt of gratitude that I owe you for getting me started down this insane and rewarding path extends far beyond the scope of a night of beer and trading stories; but I pray that our paths cross soon, that I might be able to begin repaying that debt.</p>

<p>all my best,
Mike</p>
