<div><h5>04.02.14</h5><h1>Riding</h1></div><h2>A letter to my dad</h2>

<p>man, do you remember riding? I sure do. it's come up several times in conversation over the past few weeks, each time to the wonderment of the people I tell it to. growing up, it was something of a constant: bikes were constantly a part of the landscape of my youth. and now as an adult, in a country that is somehow both rich in nature and yet utterly lacking in motocross culture, not to mention financially unable to afford such a habit, I cannot begin to express how I miss it.</p>

<p>my favorite experience still stands out as our trip to black river falls, wisconsin. the endless miles of seemingly abandoned snowmobile trails was really the first time that I began to explore the limits of my knowledge of speed; to say nothing of the insane technical single-trac trails that I so unceremoniously passed you on. you were so very sweet, letting me shred the miles on the robust KTM while you puttered along on the smaller Yamaha: though I'm sure you had an absolutely lovely trip through nature. I was simply too absorbed by the brink that I pushed both myself and the bike that I could not avoid. waiting for you at the infrequent road crossings gave me time to reflect upon this brink; some years later a friend would refer to me as an 'intense person', and it was this limit that prompted a sudden yet knowing nod of assent.</p>

<p>of course, there were other times, too! the badlands, rolling doubles, byron, ki's, bong, valpo, and the other tracks on the list that we would go through as the week would draw to an end; they all seem so close, and yet so very far away. looking back on it now, it's genuinely astounding that we put as much energy into riding as we did, even going so far as to begin an exercise regimen to boost our performances on the track. I don't know if it ever did any good; but the fervor of one father and son, and the dedication to our enjoyment is something that has stuck with me well into my creative life.</p>

<p>this is not to say that it was all fun and games. while we laugh about it now, my short-lived bout as a submarine captain did not pan out well. the process of loading and unloading at both home and track was always arduous, and care of the bikes was eternally a chore. of course, what I would now give to spend an afternoon with you tinkering on our bikes; but what really sticks out in my mind as unfortunate is the sheer amount of time I spent during travel with my headphones on. you've never been much of a talker, but my desire to shut everything out is one that I've since come to deeply regret. it was a different time, to be sure; but as our later trips would prove, striking a pleasant balance was never far from reach. though, given all of the headbanging shit that I used to listen to, I certainly couldn't blame you if you had wanted to keep it contained.</p>

<p>the parade of bikes through our lives, while incredulous to the folk I tell our story to, was one that I definitely took for granted. the rush and experience that it left in its wake while moving has left a void in my life that I find myself still trying fruitlessly to fill. but the reverence with which I hold those days is something that I will relish long into my old age, as I hope you are able to as well.</p>

<p>for making a healthy chunk of my childhood as fun to retell as it was intense:</p>

<p>thank you.</p>
